export type Styles = {
  body_click: string;
  "body-click": string;
  bodyClick: string;
  ct_bar: string;
  ct_chart_bar: string;
  ct_chart_line: string;
  ct_end: string;
  ct_grid: string;
  ct_horizontal: string;
  ct_label: string;
  ct_line: string;
  ct_point: string;
  ct_series_a: string;
  ct_slice_donut: string;
  "ct-bar": string;
  "ct-chart-bar": string;
  "ct-chart-line": string;
  "ct-end": string;
  "ct-grid": string;
  "ct-horizontal": string;
  "ct-label": string;
  "ct-line": string;
  "ct-point": string;
  "ct-series-a": string;
  "ct-slice-donut": string;
  ctBar: string;
  ctChartBar: string;
  ctChartLine: string;
  ctEnd: string;
  ctGrid: string;
  ctHorizontal: string;
  ctLabel: string;
  ctLine: string;
  ctPoint: string;
  ctSeriesA: string;
  ctSliceDonut: string;
  swal_icon_success: string;
  swal_icon_success_hide_corners: string;
  swal_modal: string;
  swal_overlay: string;
  swal_text: string;
  "swal-icon--success": string;
  "swal-icon--success__hide-corners": string;
  "swal-icon-success": string;
  "swal-icon-success-hide-corners": string;
  "swal-modal": string;
  "swal-overlay": string;
  "swal-text": string;
  swalIconSuccess: string;
  swalIconSuccessHideCorners: string;
  swalModal: string;
  swalOverlay: string;
  swalText: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
